vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "<S-h>", "<cmd>bprev<cr>", { desc = "Previous buffer", silent = true })
vim.keymap.set("n", "<S-l>", "<cmd>bnext<cr>", { desc = "Next buffer", silent = true })
vim.keymap.set("n", '<leader>so', ':SymbolsOutline<CR>', { noremap = true, silent = true })
vim.keymap.set("n", '<leader>k', '<C-u>')
vim.keymap.set("n", '<leader>j', '<C-d>')
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv") -- move line up(v)
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv") -- move line down(v)
vim.keymap.set("n", "J", ":m .+1<CR>==") -- move line up(n)
vim.keymap.set("n", "K", ":m .-2<CR>==") -- move line down(n)
vim.keymap.set("x", "p", "\"_dP")
